nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryLimits: 1024Mi
  devmemoryRequests: 512Mi
  environment:
    OAUTH_CLIENT_REDIRECT: https://${SERVICE_FQDN}/oauth2/callback
  keyVaults:
    et:
      resourceGroup: et
      secrets:
        - AppInsightsInstrumentationKey
        - idam-secret
        - redis-access-key
        - os-places-token
        - pcq-token-key
        - launch-darkly-sdk-key
idam-pr:
  enabled: false
