nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryLimits: 1024Mi
  devmemoryRequests: 512Mi
  environment:
    ET_SYA_API_HOST: http://et-cos-aat.service.core-compute-aat.internal
    OAUTH_CLIENT_REDIRECT: https://${SERVICE_FQDN}/oauth2/callback
  keyVaults:
    et:
      resourceGroup: et
      secrets:
        - app-insights-connection-string
        - idam-secret
        - et-redis-access-key
        - os-places-token
        - pcq-token-key
        - launch-darkly-sdk-key
idam-pr:
  enabled: false
