nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_NAME}.preview.platform.hmcts.net
  environment:
    OAUTH_CLIENT_REDIRECT: https://${SERVICE_NAME}.preview.platform.hmcts.net/oauth2/callback
  keyVaults:
    et:
      resourceGroup: et
      secrets:
        - AppInsightsInstrumentationKey
        - idam-secret
        - redis-access-key
        - os-places-token
        - pcq-token-key
idam-pr:
  enabled: false
