apiVersion: v2
appVersion: "1.0"
description: A Helm chart for et-sya-frontend App
name: et-sya-frontend
home: https://github.com/hmcts/et-sya-frontend
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.3.8
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'

