export const LegacyUrls = {
  ET1: 'https://employmenttribunals.service.gov.uk/en/apply/application-number',
  ET1_BASE: 'https://employmenttribunals.service.gov.uk',
  ET1_APPLY: '/apply',
  ET1_PATH: '/application-number',
  ACAS_EC_URL: 'https://www.acas.org.uk/early-conciliation',
} as const;

export const TranslationKeys = {
  COMMON: 'common',
  HOME: 'home',
  CHECKLIST: 'checklist',
  LIP_OR_REPRESENTATIVE: 'lip-or-representative',
  SINGLE_OR_MULTIPLE_CLAIM: 'single-or-multiple-claim',
  ACAS_MULTIPLE_CLAIM: 'acas-multiple',
  ADDRESS_DETAILS: 'address-details',
  DATE_OF_BIRTH: 'date-of-birth',
  SEX_AND_TITLE: 'sex-and-title',
  RETURN_TO_EXISTING: 'return-to-existing',
  TELEPHONE_NUMBER: 'telephone-number',
  UPDATE_PREFERENCE: 'update-preference',
  VALID_ACAS_REASON: 'valid-no-acas-reason',
  STILL_WORKING: 'still-working',
  VIDEO_HEARINGS: 'video-hearings',
  CONTACT_ACAS: 'contact-acas',
  PENSION: 'pension',
  JOB_TITLE: 'job-title',
  START_DATE: 'start-date',
  NOTICE_END: 'notice-end',
  NOTICE_LENGTH: 'notice-length',
  NOTICE_LENGTH_WEEKS: 'notice-length-weeks',
  NOTICE_LENGTH_MONTHS: 'notice-length-months',
  NOTICE_TYPE: 'notice-type',
  PAY: 'pay',
  AVERAGE_WEEKLY_HOURS: 'average-weekly-hours',
  BENEFITS: 'benefits',
  NOTICE_PERIOD: 'notice-period',
  NOTICE_PERIOD_WORKING: 'notice-period-working',
  NOTICE_PERIOD_NO_LONGER_WORKING: 'notice-period-no-longer-working',
  STEPS_TO_MAKING_YOUR_CLAIM: 'steps-to-making-your-claim',
  TYPE_OF_CLAIM: 'type-of-claim',
  REASONABLE_ADJUSTMENTS: 'reasonable-adjustments',
  DOCUMENTS: 'documents',
  COMMUNICATING: 'communicating',
  SUPPORT: 'support',
  COMFORTABLE: 'comfortable',
  TRAVEL: 'travel',
  NEW_JOB: 'new-job',
  NEW_JOB_START_DATE: 'new-job-start-date',
  NEW_JOB_PAY: 'new-job-pay',
  CLAIM_SUBMITTED: 'claim-submitted',
  CHECK_ANSWERS: 'check-your-answers',
  END_DATE: 'end-date',
  PAST_EMPLOYER: 'past-employer',
  CLAIM_TYPE_DISCRIMINATION: 'claim-type-discrimination',
  CLAIM_TYPE_PAY: 'claim-type-pay',
  DESCRIBE_WHAT_HAPPENED: 'describe-what-happened',
  TELL_US_WHAT_YOU_WANT: 'tell-us-what-you-want',
  COMPENSATION: 'compensation',
  TRIBUNAL_RECOMMENDATION: 'tribunal-recommendation',
  WHISTLEBLOWING_CLAIMS: 'whistleblowing-claims',
  CLAIM_DETAILS_CHECK: 'claim-details-check',
  TASK_LIST_CHECK: 'tasklist-check',
  FORM: 'form',
  RESPONDENT_NAME: 'respondent-name',
  RESPONDENT_ADDRESS: 'respondent-address',
  WORK_ADDRESS: 'work-address',
  ACAS_CERT_NUM: 'acas-cert-num',
  RESPONDENT_DETAILS_CHECK: 'respondent-details-check',
  NO_ACAS_NUMBER: 'no-acas-reason',
  WORK_POSTCODE: 'work-postcode',
  ENTER_ADDRESS: 'enter-address',
  PLACE_OF_WORK: 'place-of-work',
  COOKIE_PREFERENCES: 'cookie-preferences',
  CLAIMANT_APPLICATIONS: 'claimant-applications',
  CITIZEN_HUB: 'citizen-hub',
  CLAIM_DETAILS: 'claim-details',
  ET1_DETAILS: 'et1-details',
  SIDEBAR_CONTACT_US: 'sidebar-contact-us',
  CITIZEN_HUB_ACKNOWLEDGEMENT: 'acknowledgement-of-claim',
  CITIZEN_HUB_REJECTION: 'rejection-of-claim',
  CITIZEN_HUB_RESPONSE_REJECTION: 'response-rejection',
  CITIZEN_HUB_RESPONSE_ACKNOWLEDGEMENT: 'response-acknowledgement',
  CITIZEN_HUB_RESPONSE_FROM_RESPONDENT: 'response-from-respondent',
  CONTACT_THE_TRIBUNAL: 'contact-the-tribunal',
  TRIBUNAL_CONTACT_SELECTED: 'contact-the-tribunal-selected',
  APPLICATION_COMPLETE: 'application-complete',
  RESPOND_TO_APPLICATION_COMPLETE: 'respond-to-application-complete',
  WELSH: 'cy',
  WELSH_URL_PARAMETER: '?lng=cy',
  ENGLISH_URL_PARAMETER: '?lng=en',
  CONTACT_APPLICATION: 'contact-application',
  COPY_TO_OTHER_PARTY: 'copy-to-other-party',
  ACCESSIBILITY_STATEMENT: 'accessibility-statement',
  CONTACT_THE_TRIBUNAL_CYA: 'contact-the-tribunal-cya',
  APPLICATION_DETAILS: 'application-details',
  YOUR_APPLICATIONS: 'your-applications',
  RESPOND_TO_APPLICATION: 'respond-to-application',
  RESPONDENT_APPLICATIONS: 'respondent-applications',
  RESPONDENT_APPLICATION_DETAILS: 'respondent-application-details',
  RESPONDENT_SUPPORTING_MATERIAL: 'respondent-supporting-material',
  RESPONDENT_APPLICATION_CYA: 'respondent-application-cya',
  RESPONDENT_ORDERS_AND_REQUESTS: 'respondent-orders-and-requests',
  RESPONDENT_ORDER_OR_REQUEST_DETAILS: 'respondent-order-or-request-details',
} as const;

export const PageUrls = {
  HOME: '/',
  CHECKLIST: '/checklist',
  CLAIM_SAVED: '/your-claim-has-been-saved',
  CLAIM_STEPS: '/steps-to-making-your-claim',
  CLAIM_SUBMITTED: '/your-claim-has-been-submitted',
  RETURN_TO_EXISTING: '/return-to-existing',
  LIP_OR_REPRESENTATIVE: '/lip-or-representative',
  SINGLE_OR_MULTIPLE_CLAIM: '/single-or-multiple-claim',
  ACAS_MULTIPLE_CLAIM: '/do-you-have-an-acas-no-many-resps',
  VALID_ACAS_REASON: '/do-you-have-a-valid-no-acas-reason',
  STILL_WORKING: '/are-you-still-working',
  TYPE_OF_CLAIM: '/type-of-claim',
  NEW_ACCOUNT_LANDING: '/new-account-landing',
  DOB_DETAILS: '/dob-details',
  ADDRESS_DETAILS: '/address-details',
  CONTACT_ACAS: '/contact-acas',
  VIDEO_HEARINGS: '/would-you-want-to-take-part-in-video-hearings',
  TELEPHONE_NUMBER: '/telephone-number',
  SEX_AND_TITLE: '/sex-and-title',
  UPDATE_PREFERENCES: '/how-would-you-like-to-be-updated-about-your-claim',
  JOB_TITLE: '/job-title',
  PAST_EMPLOYER: '/past-employer',
  PENSION: '/pension',
  START_DATE: '/start-date',
  NOTICE_END: '/notice-end',
  NOTICE_LENGTH: '/notice-length',
  NOTICE_TYPE: '/notice-type',
  PAY: '/pay',
  AVERAGE_WEEKLY_HOURS: '/average-weekly-hours',
  BENEFITS: '/benefits',
  NOTICE_PERIOD: '/got-a-notice-period',
  CHECK_ANSWERS: '/check-your-answers',
  PLACE_OF_WORK: '/place-of-work',
  ADDRESS_LOOK_UP: '/address-lookup',
  REASONABLE_ADJUSTMENTS: '/reasonable-adjustments',
  DOCUMENTS: '/documents',
  COMMUNICATING: '/communicating',
  SUPPORT: '/support',
  COMFORTABLE: '/comfortable',
  TRAVEL: '/travel',
  NEW_JOB: '/new-job',
  NEW_JOB_START_DATE: '/new-job-start-date',
  NEW_JOB_PAY: '/new-job-pay',
  END_DATE: '/end-date',
  CLAIM_TYPE_DISCRIMINATION: '/claim-type-discrimination',
  CLAIM_TYPE_PAY: '/claim-type-pay',
  DESCRIBE_WHAT_HAPPENED: '/describe-what-happened',
  TELL_US_WHAT_YOU_WANT: '/tell-us-what-you-want',
  COMPENSATION: '/compensation',
  TRIBUNAL_RECOMMENDATION: '/tribunal-recommendation',
  WHISTLEBLOWING_CLAIMS: '/whistleblowing-claims',
  PERSONAL_DETAILS_CHECK: '/personal-details-check',
  CLAIM_DETAILS_CHECK: '/claim-details-check',
  RESPONDENT_NAME: '/respondent-name',
  RESPONDENT_ADDRESS: '/respondent-address',
  WORK_ADDRESS: '/work-address',
  ACAS_CERT_NUM: '/acas-cert-num',
  RESPONDENT_DETAILS_CHECK: '/respondent-details-check',
  NO_ACAS_NUMBER: '/no-acas-reason',
  EMPLOYMENT_RESPONDENT_TASK_CHECK: '/employment-respondent-task-check',
  WORK_POSTCODE: '/work-postcode',
  RESPONDENT_REST_PREFIX: '/respondent/:respondentNumber',
  FIRST_RESPONDENT_NAME: '/respondent/1/respondent-name',
  CLAIMANT_APPLICATIONS: '/claimant-applications',
  SELECTED_APPLICATION: '/claimant-application/:caseId',
  COOKIE_PREFERENCES: '/cookies',
  CITIZEN_HUB: '/citizen-hub/:caseId',
  CLAIM_DETAILS: '/claim-details',
  CITIZEN_HUB_DOCUMENT: '/case-document/:documentType',
  CITIZEN_HUB_DOCUMENT_RESPONSE_RESPONDENT: '/case-document/' + TranslationKeys.CITIZEN_HUB_RESPONSE_FROM_RESPONDENT,
  GET_CASE_DOCUMENT: '/getCaseDocument/:docId',
  GET_SUPPORTING_MATERIAL: '/getSupportingMaterial',
  CONTACT_THE_TRIBUNAL: '/contact-the-tribunal',
  TRIBUNAL_CONTACT_SELECTED: '/contact-the-tribunal/:selectedOption',
  REMOVE_FILE: '/remove-tse-file/:application',
  PCQ: '/pcq',
  PCQ_WELSH: '/pcq?lng=cy',
  CONTACT_APPLICATION: '/contact-application',
  COPY_TO_OTHER_PARTY: '/copy-to-other-party',
  CONTACT_THE_TRIBUNAL_CYA: '/contact-the-tribunal-cya',
  APPLICATION_COMPLETE: '/application-complete',
  ACCESSIBILITY_STATEMENT: '/accessibility',
  APPLICATION_DETAILS: '/application-details/:appId',
  RESPOND_TO_APPLICATION_SELECTED: '/respond-to-application/:appId',
  RESPOND_TO_APPLICATION: '/respond-to-application',
  YOUR_APPLICATIONS: '/your-applications',
  RESPONDENT_APPLICATIONS: '/respondent-applications',
  RESPONDENT_APPLICATION_DETAILS: '/respondent-application-details/:appId',
  RESPONDENT_SUPPORTING_MATERIAL: '/respondent-supporting-material/:appId',
  REMOVE_SUPPORTING_MATERIAL: '/remove-supporting-material/:appId',
  RESPOND_TO_APPLICATION_COMPLETE: '/respond-to-application-complete',
  RESPONDENT_APPLICATION_CYA: '/respondent-application-cya',
  RESPONDENT_ORDERS_AND_REQUESTS: '/respondent-orders-and-requests',
  RESPONDENT_ORDER_OR_REQUEST_DETAILS: '/respondent-order-or-request-details/:orderId',
  GET_TRIBUNAL_ORDER_DOCUMENT: '/getTribunalOrderDocument/:docId',
} as const;

export const InterceptPaths = {
  CHANGE_DETAILS: '*/change',
  ANSWERS_CHANGE: '/change?redirect=answers',
  RESPONDENT_CHANGE: '/change?redirect=respondent',
  SUBMIT_CASE: '/submitDraftCase',
  REMOVE_FILE: '/remove-uploaded-file',
  SUBMIT_TRIBUNAL_CYA: '/submitTribunalCya',
  SUBMIT_RESPONDENT_CYA: '/submitRespondentCya',
} as const;

export const ErrorPages = {
  NOT_FOUND: '/not-found',
};

export const ValidationErrors = {
  REQUIRED: 'required',
  INVALID_VALUE: 'invalid',
} as const;

export const AuthUrls = {
  CALLBACK: '/oauth2/callback',
  LOGIN: '/login',
  LOGOUT: '/logout',
} as const;

export const JavaApiUrls = {
  GET_CASES: 'cases/user-cases',
  GET_CASE: 'cases/user-case',
  INITIATE_CASE_DRAFT: 'cases/initiate-case',
  UPDATE_CASE_DRAFT: 'cases/update-case',
  SUBMIT_CASE: 'cases/submit-case',
  UPDATE_CASE_SUBMITTED: 'cases/update-hub-links-statuses',
  SUBMIT_CLAIMANT_APPLICATION: 'cases/submit-claimant-application',
  DOWNLOAD_CLAIM_PDF: '/generate-pdf',
  UPLOAD_FILE: '/documents/upload/',
  DOCUMENT_DOWNLOAD: '/document/download/',
  DOCUMENT_DETAILS: '/document/details/',
} as const;

export const Urls = {
  INFO: '/info',
  DOWNLOAD_CLAIM: '/download-claim',
  PCQ: '/pcq',
  EXTEND_SESSION: '/extend-session',
} as const;

export const HTTPS_PROTOCOL = 'https://';

export const ALLOWED_FILE_FORMATS = [
  'pdf',
  'doc',
  'docx',
  'txt',
  'dot',
  'jpg',
  'jpeg',
  'bmp',
  'tif',
  'tiff',
  'png',
  'pdf',
  'xls',
  'xlt',
  'xla',
  'xlsx',
  'xltx',
  'xlsb',
  'ppt',
  'pot',
  'pps',
  'ppa',
  'pptx',
  'potx',
  'ppsx',
  'rtf',
  'csv',
];

export const RedisErrors = {
  REDIS_ERROR: 'redisError',
  DISPLAY_MESSAGE: 'Please try again or return later.',
  FAILED_TO_CONNECT: 'Error when attempting to connect to Redis',
  FAILED_TO_SAVE: 'Error when attempting to save to Redis',
  FAILED_TO_RETRIEVE: 'Error when attempting to retrieve value from Redis',
  CLIENT_NOT_FOUND: 'Redis client does not exist',
} as const;

export const CaseApiErrors = {
  FAILED_TO_RETRIEVE_CASE: 'Error when attempting to retrieve draft case from sya-api',
} as const;

export const CcdDataModel = {
  CASE_SOURCE: 'ET1 Online',
} as const;

export const EXISTING_USER = 'existingUser';
export const LOCAL_REDIS_SERVER = '127.0.0.1';
export const CITIZEN_ROLE = 'citizen';
export const TYPE_OF_CLAIMANT = 'Individual';
export const FILE_SIZE_LIMIT = 83886500;

export const inScopeLocations = [
  'ZE',
  'TD9',
  'TD8',
  'TD7',
  'TD6',
  'TD5',
  'TD4',
  'TD3',
  'TD2',
  'TD14',
  'TD13',
  'TD11',
  'TD10',
  'TD1',
  'PH',
  'PA',
  'ML',
  'KY',
  'KW',
  'KA',
  'IV',
  'HS',
  'G',
  'FK',
  'EH',
  'DG',
  'DD',
  'AB',
  'YO',
  'WF',
  'S',
  'OL14',
  'LS',
  'HX',
  'HU',
  'HG',
  'HD',
  'DN',
  'BD',
  // Bristol
  'TR',
  'TQ',
  'TA',
  'SP',
  'SO',
  'SN',
  'RG28',
  'RG27',
  'RG26',
  'RG25',
  'RG24',
  'RG23',
  'RG22',
  'RG21',
  'PO',
  'PL',
  'GU35',
  'GU34',
  'GU33',
  'GU32',
  'GU31',
  'GU30',
  'GU29',
  'GU28',
  'GU27',
  'GU26',
  'GL',
  'EX',
  'DT',
  'BS',
  'BN45',
  'BN44',
  'BN43',
  'BN18',
  'BN17',
  'BN16',
  'BN15',
  'BN14',
  'BN13',
  'BN12',
  'BN11',
  'BH',
  'BA',
  // Midlands East
  'S81',
  'S80',
  'S45',
  'S44',
  'S43',
  'S42',
  'S41',
  'S40',
  'PE25',
  'PE24',
  'PE23',
  'PE22',
  'PE21',
  'PE20',
  'PE12',
  'PE11',
  'PE10',
  'NG',
  'LN',
  'LE',
  'DN41',
  'DN37',
  'DN36',
  'DN35',
  'DN34',
  'DN33',
  'DN32',
  'DN31',
  'DN22',
  'DN21',
  'DE',
];

export const et1DocTypes = ['ET1'];
export const acceptanceDocTypes = ['1.1', 'Acknowledgement of Claim'];
export const rejectionDocTypes = ['Rejection of claim'];
export const responseAcceptedDocTypes = ['2.11'];
export const responseRejectedDocTypes = ['2.12', '2.13', '2.14', '2.15'];
export const et3FormDocTypes = ['ET3'];
export const CHANGE = 'Change';

export const languages = {
  WELSH: 'cy',
  ENGLISH: 'en',
  WELSH_LOCALE: '&ui_locales=cy',
  ENGLISH_LOCALE: '&ui_locales=en',
  WELSH_URL_PARAMETER: '?lng=cy',
  ENGLISH_URL_PARAMETER: '?lng=en',
};

export const Rule92Types = {
  CONTACT: 'Contact',
  RESPOND: 'Respond',
  TRIBUNAL: 'Tribunal',
} as const;

export const Parties = {
  BOTH_PARTIES: 'Both parties',
  CLAIMANT_ONLY: 'Claimant only',
  RESPONDENT_ONLY: 'Respondent only',
} as const;

export const ResponseRequired = {
  YES: 'Yes - view document for details',
  NO: 'No',
} as const;
